[template]
src = "jvm.config.tmpl"
dest = "/var/presto/data/etc/jvm.config"

keys = [ 
   "/java/maxheap/size",
   "/java/perm/size",
   "/java/maxperm/size",
   "/java/rccs/size",
   "/presto/rootdir"
]
